name: Update ArmoniK.Api

on:
  push:
    branches:
      - main
    paths:
      - '**.proto'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${{github.event.head_commit.committer.name}}"
          git config --global user.email "${{github.event.head_commit.committer.email}}"
  
      - name: Clone ArmoniK.Api
        run: |
          git clone https://${{ secrets.ARMONIK_GH_TOKEN }}@github.com/aneoconsulting/ArmoniK.Api.git --recursive

      - name: Update ArmoniK.Api
        run: |
          cd ArmoniK.Api
          git submodule update --remote

      - name: Modify ArmoniK.Api
        run: |
          cd ArmoniK.Api
          git commit -a -m "${{github.event.head_commit.message}}"
          git show

      - name: Push ArmoniK.Api
        run: |
          cd ArmoniK.Api
          git push origin $(git rev-parse --abbrev-ref HEAD)
